name: textlint

on:
  push:
    branches: [ main ]

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install textlint
        run: >
          npm install --save-dev
          textlint
          textlint-rule-preset-smarthr
          textlint-rule-prh
          textlint-filter-rule-allowlist

      - name: Install dependent module
        run: npm install

      - name: Execute textlint
        run: npx textlint "articles/**/*.md"